version: '3.4'

services:
  telegrambot.service:
    image: ${DOCKER_REGISTRY-}telegrambotservice
    ports:
        - "5000:80" 
    build:
      context: .
      dockerfile: TelegramBot.WebApi/Dockerfile
    depends_on:
        - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "BkmzRkbitdbx00!"
        ACCEPT_EULA: "Y"       
    ports:
        - "1433:1433"
    volumes:
        - tgbot-db:/var/opt/mssql/

volumes:
  tgbot-db:
   