version: '3.4'

services:
  telegrambot.service:
    image: ${DOCKER_REGISTRY-}telegrambotservice
    container_name: tgbot-service
    ports:
        - "5000:80"    
    build:
      context: .
      dockerfile: TelegramBot.WebApi/Dockerfile
    depends_on:
        - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: db-tgbot
    environment:
        SA_PASSWORD: "BkmzRkbitdbx00!"
        ACCEPT_EULA: "Y"       
    ports:
        - "1433:1433"
    volumes:
        - tgbot-db:/var/opt/mssql/    

  nginx:
    image: "nginx"
    container_name: nginx
    ports:
        - "80:80"
    depends_on:
        - telegrambot.service
    volumes:
        - ./TelegramBot.Proxy/nginx.conf:/etc/nginx/nginx.conf

 
volumes:
  tgbot-db:
  
   